project:
  type: website
  output-dir: "docs"

website:
  title: "RDIE WiSe 22"
  navbar:
    left:
      - href: Vorlesung.qmd
        text: "Lecture"
      - href: uebung.qmd
        text: "Exercise"
  
format:
  html:
    theme: darkly
    css: styles.css
    toc: true

editor: visual

