---
title: 'Recent Developments in Econometrics (Winter 2022/23)'
subtitle: "Chair of Econometrics "
---

Aufgrund der aktuellen technischen Probleme bei den Informationsdiensten der Universität stellen wir Materialien für den Kurs *Deskriptive Statistik* kurzfristig über diese Website bereit. Beachten Sie, dass `JACK` von der Störung genauso betroffen ist wie alle anderen Dienste.

**Bitte beachten Sie, dass sämtliche E-Mail-Dienste der Universität ebenfalls betroffen sind. Daher haben wir die nachfolgenden E-Mail-Adressen für Sie eingerichtet.**

## Kontakt

Bei **wichtigen** Fragen wenden Sie sich bitte per E-Mail an uns:

-   [Jens Klenke](mailto:jens.klenke.ude@gmail.com?subject=%5BDeskriptive%20Statistik%5D)
-   [Christoph Hanck](mailto:christoph.hanck@uni-dortmund.de?subject=%5BDeskriptive%20Statistik%5D)

## Testate

Aufgrund der technischen Störungen an der Universität Duisburg-Essen wird das 2. Tests, geplant am 30.11.2022, auf unbestimmte Zeit verschoben. Wir werden Sie über Änderungen frühzeitig informieren.

```{=html}
<!--
## Discord: Diskussions- und Nachrichtenforum

<iframe src="https://e.widgetbot.io/channels/1046707102984437770/1046707119774236694" height="600" width="100%"></iframe>
-->
```
